TOOLCHAIN_VERSION:=1.0.0

all:
	@echo "make toolchain-image"

toolchain-image:
	docker build -t toolchain:$(TOOLCHAIN_VERSION) -f Dockerfile.toolchain .
	docker tag toolchain:$(TOOLCHAIN_VERSION) toolchain:latest
